parameters:
#    kss_bridge.example.class: Kss\Bundle\BridgeBundle\Example

services:
#    kss_bridge.example:
#        class: %kss_bridge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
