parameters:
#    scan_kss.example.class: Scan\Bundle\KssBundle\Example

services:
#    scan_kss.example:
#        class: %scan_kss.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
